### PR TITLE
Dark Theme for Player Config UI

### PR DESCRIPTION
**Pull request by fyffep**
This is part one of a planned UI overhaul. After this PR, I'd like to add in a light theme option as well as apply the themes to the rest of Player5. 

https://github.com/CompuCell3D/cc3d-player5/assets/79017811/2685964a-b0b9-4165-9dbe-b510a64a3962

### CODE REVIEW

**Comment by fyffep** [comment]
Also... I was thinking about having every change to the settings auto-save. It's confusing that some do and some do not. I can hit the 'Esc' button accidentally after changing many settings only to lose the progress. After all, how often would a person change a setting only to decide to erase those changes?

**Comment by maciekswat** [comment]
Autosave is a good idea but for this we would need to intercept every user change and store just those changes. As of now I think all the settings are written back to the settings database

**Comment by maciekswat** [comment]
can also have an option where we can toggle between stylesheets? We would also need to add a setting that remembers the stylesheet

**Comment by fyffep** [comment]
> Autosave is a good idea but for this we would need to intercept every user change and store just those changes. As of now I think all the settings are written back to the settings database

I meant that every change where you have to click the "OK" button to save to the database would instead save to the database immediately. I've even been inconsistent myself with between these two approaches. It wouldn't be so bad to make this fix.

**Comment by fyffep** [comment]
> can also have an option where we can toggle between stylesheets? We would also need to add a setting that remembers the stylesheet

I finished adding a light and dark theme. It's in a separate branch, `feature/themes`

**Pull request closed without merging**
