### PR TITLE
Feature/demo panel

### PR DESCRIPTION
**Pull request by fyffep**
To test this, run the SQLite command: ``INSERT INTO settings (name,type,value) VALUES('DemosPath','str','');``
Next, click the menu Help -> Open Demo. You can search for demos, preview their XML/Python files, and open them.

Demos are indexed according to:
1. key words in their Python files
2. XML attributes
3. the paths and names
4. the words in the README.txt file found in the directory of the demo

Known bugs:
1. When closing Player after running a demo that was opened through this menu, the console will print:
```
swig/python detected a memory leak of type 'CC3DXMLElement *', no destructor found.
swig/python detected a memory leak of type 'CC3DXMLElement *', no destructor found.
swig/python detected a memory leak of type 'CC3DXMLElement *', no destructor found.
swig/python detected a memory leak of type 'CC3DXMLElement *', no destructor found.
```
2. MaBoSSDemo will be formatted as Ma Ba SS Demo

Next steps: Every demo will need a README.txt file to provide a short description of what it does.

### CODE REVIEW

**Comment by fyffep** [comment]
image

**Comment by maciekswat** [comment]
@fyffep I thought it would be helpful if you could issue separate PR for _openSim->_openSimDialog changes to SImpleTabView - I will send you your file separately in the email but you can also get it from git history. I had to resolve a few conflicts related to UI themes - maybe you created your branch using the theme branch and this is why those changes showed up here.

**Comment by maciekswat** [comment]
regarding those errors - I dont see them on OSX. What are the steps that reproduce them?
swig/python detected a memory leak of type 'CC3DXMLElement *', no destructor found.
swig/python detected a memory leak of type 'CC3DXMLElement *', no destructor found.
swig/python detected a memory leak of type 'CC3DXMLElement *', no destructor found.
swig/python detected a memory leak of type 'CC3DXMLElement *', no destructor found.

**Comment by maciekswat** [comment]
BTW you will need to pull from git to get all the changes I merged to your branch from develop

**Comment by fyffep** [comment]
@maciekswat Steps to reproduce:
1. Open Player
2. Click Help -> Open Demo
3. Click on _any_ demo, such as CellSort2D
4. Click Step
5. Click Stop
6. Close Player

Result:
```
INSIDE handleSimulationFinishedRegular
Making movie inside ` C:\Users\Pete\CC3DWorkspace\elasticityTestFlexExternalPotential_cc3d_01_28_2024_18_20_47 `
Created 0 movies inside `C:\Users\Pete\CC3DWorkspace\elasticityTestFlexExternalPotential_cc3d_01_28_2024_18_20_47` with frame rate 4 and quality 7/51.
EXITING WITH ERROR CODE= 0
swig/python detected a memory leak of type 'CC3DXMLElement *', no destructor found.
swig/python detected a memory leak of type 'CC3DXMLElement *', no destructor found.
swig/python detected a memory leak of type 'CC3DXMLElement *', no destructor found.
swig/python detected a memory leak of type 'CC3DXMLElement *', no destructor found.
swig/python detected a memory leak of type 'CC3DXMLElement *', no destructor found.
swig/python detected a memory leak of type 'CC3DXMLElement *', no destructor found.
```

**Comment by fyffep** [comment]
> ```
> swig/python detected a memory leak of type 'CC3DXMLElement *', no destructor found.
> ```

Bug has been resolved by [9ba19ae](https://github.com/CompuCell3D/cc3d-player5/pull/49/commits/9ba19ae99437d33fa0954e3111ef7e538b8c2a26).

The new PR #49 replaces this one.

**Pull request closed without merging**
